services:
  # auth_service:
  #   build:
  #     context: ./services/auth.service.clrtech
  #   container_name: bookstoreclr_auth_service
  #   depends_on:
  #     - sqlserver
  #     - rabbitmq_server

  # catalog_service:
  #   build:   
  #     context: ./services/catalog.service.clrtech
  #   container_name: bookstoreclr_catalog_service
  #   depends_on:
  #     - mysql_server
  #     - rabbitmq_server

  # shopping_service:
  #   build:
  #     context: ./services/shopping.service.clrtech
  #   container_name: bookstoreclr_shopping_service
  #   depends_on:
  #     - redis_server
  #     - rabbitmq_server

  # order_service:
  #   build:
  #     context: ./services/order.service.clrtech
  #   container_name: bookstoreclr_order_service
  #   depends_on:
  #     - sqlserver
  #     - rabbitmq_server

  # payment_service:
  #   build:
  #     context: ./services/payment.service.clrtech
  #   container_name: bookstoreclr_payment_service
  #   depends_on:
  #     - sqlserver
  #     - rabbitmq_server

  redis_server:
    build:
      context: ./manifests/configurations/redis
    ports:
      - "6379:6379"
    volumes:
      - redis_datad_dev:/data
      - ./manifests/configurations/redis/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: bookstoreclr_redis_server

  mysql_server:
    build:
      context: ./manifests/configurations/mysql
    container_name: bookstoreclr_mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    ports:
      - "3306:3306"
    volumes:
      - mysql_datad_dev:/var/lib/mysql

  cloudbeaver_server:
    build:
      context: ./manifests/configurations/cloudbeaver
    container_name: bookstoreclr_cloudbeaver_server
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_datad_dev:/opt/cloudbeaver/workspace
   
  sqlserver:
    build:
      context: ./manifests/configurations/sqlserver
    container_name: bookstoreclr_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Str0ngPa5sVvorcl"
      MSSQL_DATABASE: sqlserver_db
    volumes:  
      - sqlserver_datad_dev:/var/opt/mssql
   
  rabbitmq_server:
    build:
      context: ./manifests/configurations/rabbitmq
    container_name: bookstoreclr_rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_datad_dev:/var/lib/rabbitmq
   

  # nginx_server:
  #   build:
  #     context: ./manifests/configurations/nginx
  #   container_name: bookstoreclr_nginx_server
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - auth_service
  #     - catalog_service
  #     - shopping_service
  #     - order_service
  #     - payment_service
  #   volumes:
  #     - ./manifests/configurations/nginx/nginx-dev.conf:/etc/nginx/nginx.conf

volumes:
  mysql_datad_dev:
  cloudbeaver_datad_dev:
  sqlserver_datad_dev:
  rabbitmq_datad_dev:
  redis_datad_dev: